---
  - name: "linux-laptop"
    hosts: localhost
    connection: local
    tasks:

    - name: "install packages"
      become: true
      ansible.builtin.package:
        state: present
        name:
          - git
          - openssh
          - tmux
          - task
          - man-db
          - less
          - slim
          - i3
          - rofi
          - rxvt-unicode
          - xorg-server
          - xorg-xrdb
          - power-profiles-daemon
          - python-gobject
          - firefox
          - sof-firmware
          - pulseaudio
          - alsa-utils
          - rsync
          - hsetroot
          - polybar
          - cronie
          - cmake
          - picom
          - gcc
          - make
          - nitrogen
          - maim
          - xclip
          - dex
          - xautolock
          - autorandr
          - pavucontrol
          - brightnessctl
          - glow

    - name: service-cronie
      become: true
      service:
        state: started
        enabled: true
        name: cronie

    - name: service-slim
      become: true
      service:
        state: started
        enabled: true
        name: slim

    - name: service-power-profiles-daemon
      become: true
      service:
        state: started
        enabled: true
        name: power-profiles-daemon

    - name: "time sync"
      become: true
      service:
        state: started
        enabled: true
        name: systemd-timesyncd
