---
  - name: "linux-laptop"
    hosts: localhost
    connection: local
    tasks:

    - name: util-packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - openssh
          - tmux
          - task
          - man-db
          - less
        state: present

    - name: "locale.conf"
      become: true
      copy:
        dest: /etc/locale.conf
        content: |
          LANG=en_US.UTF-8
          LANGUAGE=en_US.UTF-8
          LC_ALL=en_US.UTF-8

    - name: desktop-packages
      become: true
      ansible.builtin.package:
        state: present
        name:
          - slim
          - i3
          - rofi
          - rxvt-unicode
          - xorg-server
          - xorg-xrdb
          - power-profiles-daemon
          - python-gobject
          - firefox
          - sof-firmware
          - xsel

    - name: service-slim
      become: true
      service:
        state: started
        enabled: true
        name: slim

    - name: service-power-profiles-daemon
      become: true
      service:
        state: started
        enabled: true
        name: power-profiles-daemon

    - name: "xinit"
      copy:
        dest: ~/.xinitrc
        content: |
          xrdb ~/.Xresources
          i3
    - name: "i3-config"
      ansible.builtin.copy:
        src: home/.config/i3/config
        dest: ~/.config/i3/config
