---
  - name: "linux-laptop"
    hosts: localhost
    connection: local
    tasks:

    - name: util-packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - openssh
          - tmux
          - task
        state: present

    - name: desktop-packages
      become: true
      ansible.builtin.package:
        state: present
        name:
          - slim
          - i3
          - rofi
          - rxvt-unicode
          - xorg-server
          - xorg-xrdb
          - power-profiles-daemon
          - python-gobject

    - name: service-slim
      become: true
      service:
        state: started
        enabled: true
        name: slim

    - name: service-power-profiles-daemon
      become: true
      service:
        state: started
        enabled: true
        name: power-profiles-daemon

    - name: "i3-config"
      ansible.builtin.copy:
        src: home/.config/i3/config
        dest: ~/.config/i3/config
