---
  - name: "linux-laptop"
    hosts: localhost
    connection: local
    tasks:

    - name: util-packages
      ansible.builtin.package:
        name:
          - git
          - openssh
          - tmux
          - task
        state: present

    - name: desktop-packages
      ansible.builtin.package:
        state: present
        name:
          - slim
          - i3
          - rofi
          - rxvt-unicode
          - xorg-server
          - xorg-xrdb
          - power-profiles-daemon
          - python-gobject
