---
  - name: "linux-laptop"
    hosts: localhost
    connection: local
    tasks:

    - name: "locale.conf"
      become: true
      copy:
        dest: /etc/locale.conf
        content: |
          LANG=en_US.UTF-8
          LANGUAGE=en_US.UTF-8
          LC_ALL=en_US.UTF-8

    - name: "install packages"
      become: true
      ansible.builtin.package:
        state: present
        name:
          - git
          - openssh
          - tmux
          - task
          - man-db
          - less
          - slim
          - i3
          - rofi
          - rxvt-unicode
          - xorg-server
          - xorg-xrdb
          - power-profiles-daemon
          - python-gobject
          - firefox
          - sof-firmware
          - xsel
          - ncspot
          - pulseaudio
          - alsa-utils
          - rsync
          - hsetroot
          - polybar

    - name: service-slim
      become: true
      service:
        state: started
        enabled: true
        name: slim

    - name: service-power-profiles-daemon
      become: true
      service:
        state: started
        enabled: true
        name: power-profiles-daemon
