---
  - name: "user profile"
    hosts: localhost
    connection: local
    tasks:

    - name: "xinitrc"
      copy:
        dest: ~/.xinitrc
        content: |
          xrdb ~/.Xresources
          i3

    - name: "i3 config"
      ansible.builtin.copy:
        src: home/.config/i3/config
        dest: ~/.config/i3/config

    - name: "Xresources"
      copy:
        src: home/.Xresources
        dest: ~/.Xresources

    - name: "vimrc"
      copy:
        src: home/.vimrc
        dest: ~/.vimrc

    - name: "polybar"
      copy:
        src: home/.config/polybar/config.ini
        dest: ~/.config/polybar/config.ini

    - name: "tmux"
      copy:
        src: home/.tmux.conf
        dest: ~/.tmux.conf

