---
  - name: "user profile"
    hosts: localhost
    connection: local
    tasks:

    - name: "xinitrc"
      copy:
        dest: ~/.xinitrc
        content: |
          xrdb ~/.Xresources
          i3

    - name: "i3 config"
      ansible.builtin.copy:
        src: home/.config/i3/config
        dest: ~/.config/i3/config

    - name: "Xresources"
      copy:
        src: home/.Xresources
        dest: ~/.Xresources

    - name: "vimrc"
      copy:
        src: home/.vimrc
        dest: ~/.vimrc

    - name: "ycm"
      file:
        state: directory
        path: ~/.vim/bundle/YouCompleteMe
      register: ycm

    - name: "ycm install"
      command: "{{ item.cmd }}"
      args:
        chdir: "{{ item.chdir }}"
      with_items:
      - { chdir: ~/.vim/bundle, cmd: git clone https://github.com/ycm-core/YouCompleteMe.git }
      - { chdir: ~/.vim/bundle/YouCompleteMe, cmd: git submodule update --init --recursive }
      - { chdir: ~/.vim/bundle/YouCompleteMe, cmd: python3 install.py }
      when: ycm is changed

    - name: "polybar"
      copy:
        src: home/.config/polybar/config.ini
        dest: ~/.config/polybar/config.ini

    - name: "polybar config.d"
      file:
        state: directory
        path: ~/.config/polybar/config.d

    - name: "tmux"
      copy:
        src: home/.tmux.conf
        dest: ~/.tmux.conf

    - name: "alacritty config dir"
      file:
        state: directory
        path: ~/.config/alacritty

    - name: "alacritty.toml"
      copy:
        src: home/.config/alacritty/alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml

    - name: "alacritty themes dir"
      stat:
        path: ~/.config/alacritty/alacritty-theme
      register: alacritty_theme

    - name: "clone alacritty-theme"
      command: git clone https://github.com/alacritty/alacritty-theme
      args:
        chdir: ~/.config/alacritty/
      when: not alacritty_theme.stat.exists

