- name: "tmux"
  copy:
    src: home/.tmux.conf
    dest: ~/.tmux.conf

- name: "vim bundle dir"
  file:
    state: directory
    path: ~/.vim/bundle

- name: "vimrc"
  copy:
    src: home/.vimrc
    dest: ~/.vimrc

- name: "ycm"
  file:
    state: directory
    path: ~/.vim/bundle/YouCompleteMe
  register: ycm

- name: "ycm install"
  command: "{{ item.cmd }}"
  args:
    chdir: "{{ item.chdir }}"
  with_items:
  - { chdir: ~/.vim/bundle, cmd: git clone https://github.com/ycm-core/YouCompleteMe.git }
  - { chdir: ~/.vim/bundle/YouCompleteMe, cmd: git submodule update --init --recursive }
  - { chdir: ~/.vim/bundle/YouCompleteMe, cmd: python3 install.py }
  when: ycm is changed

- name: "ssh config.d"
  file:
    state: directory
    path: ~/.ssh/config.d
    mode: "700"

- name: "ssh config"
  copy:
    src: home/.ssh/config
    dest: ~/.ssh/config
    mode: "600"
