[general]
live_config_reload = true

import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[window]
opacity = 0.95

[font]
normal = { family = "Azeret Mono", style="Medium" }
bold = { style="Medium" }
italic = { style="Medium" }
bold_italic = { style="Medium" }
size = 10
offset.x =  0
offset.y = -2
