live_config_reload = true

import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[window]
opacity = 0.95

[font]
normal = { family = "Azeret Mono", style="Regular" }
bold = { style="Regular" }
italic = { style="Regular" }
bold_italic = { style="Regular" }
size = 11
